### ISSUE TITLE
PCL support

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [Cheesebaron/Cheesebaron.MvxPlugins#58]
Hello,

I was just doing the MvvmCross 4.0 update this morning and found that after updating your settings plugin it couldn't be added to my core project as the PCL profile is no longer supported. I am not sure if this is a deliberate change? It is PCL 4.5 - Profile259 using Xamarin Studio on a Mac.

This is the error : 
Could not install package 'Cheesebaron.MvxPlugins.Settings 1.2.3'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Cheers,
Ryan

**Comment by Cheesebaron** [comment]
It has been fixed, I pushed out new packages :)

**Comment by RyanBuzzInteractive** [comment]
Fantastic, thank you!!

**Comment by Cheesebaron** [comment]
Wait sorry. You tried installing 1.2.3? That is where the fix should be. What happens if you try installing 1.2.2 instead?

**Comment by Cheesebaron** [comment]
Problem here might be the wp80 target, are you using that? Try removing that from your PCL profile.

**Comment by RyanBuzzInteractive** [comment]
I was running 1.2.2 pre-4 which was fine. I updated to 1.2.3 which prevented it being added to the PCL.  This is my config:
<img width="714" alt="screen shot 2016-02-05 at 11 40 30" src="https://cloud.githubusercontent.com/assets/10651463/12845391/545e741e-cbfd-11e5-95c1-ab50644bbab1.png">

**Comment by Cheesebaron** [comment]
In any case, I am using the same profile as MvvmCross 4.0.0 for packing the PCL, so if you can add MvvmCross 4.0.0, this should also be the case for this plugin starting with version 1.2.3.

Windows Phone Silverlight support has ended in MvvmCross and in this plugin long ago.

**Comment by RyanBuzzInteractive** [comment]
The official Xamarin one that James made still installs ok too, I tried swapping to it earlier and it has been a massive headache as it doesn't have all of your extensions. MvvmCross 4.0 and all other plugins are installing fine too.

**Comment by RyanBuzzInteractive** [comment]
The only reason we have all of those selected is that we are making a mobile top up app for a very big supermarket chain (the biggest) and they have a requirement for us to support everything ever :(

**Comment by Cheesebaron** [comment]
Let me dig a bit, will return to you soon.

**Comment by RyanBuzzInteractive** [comment]
No worries, thanks for your help :) Much appreciated. You guys are legends ^_^

**Comment by Cheesebaron** [comment]
Sorry, this is actually my mistake. I see I still have a WindowsPhone project which is a 8.0 one. Will fix the PCL issue as it is missing a target. Pushing new packages very soon :)

**Comment by Cheesebaron** [comment]
Could you please try again, I've pushed 1.2.4 to NuGet now.

**Comment by RyanBuzzInteractive** [comment]
Honestly, you guys provide better support for nothing than most of the commercial companies we work with. Thanks so much for getting on it this quickly :) Will give it a go now.

**Comment by RyanBuzzInteractive** [comment]
hmmm I still get 
Could not install package 'Cheesebaron.MvxPlugins.Settings 1.2.4'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Cheesebaron** [comment]
I just created a new PCL with the following targets and added the plugin no problem:

![Imgur](http://i.imgur.com/xVh1Hz8.png)

Not sure what is going on. Do you have the possibility to do this from VS instead?

**Comment by RyanBuzzInteractive** [comment]
I can, yeah, I'll switch to my VM and give it a go. I noticed this from a couple of hours ago, seemed to have the droid / ios platforms removed? Should your new commits be showing in GitHub as I can't see a commit from the last 30 mins. 
<img width="1349" alt="screen shot 2016-02-05 at 11 55 51" src="https://cloud.githubusercontent.com/assets/10651463/12845725/db5897e0-cbff-11e5-85f1-bcfeb021c1b8.png">

**Comment by Cheesebaron** [comment]
That should not be a problem as MonoDroid and Xamarin.iOS are automatically targets.

**Comment by RyanBuzzInteractive** [comment]
Ah ok :)

**Comment by RyanBuzzInteractive** [comment]
Just booting up the VM. Tried a blank Xamarin Studio PCL project with the same config I pasted earlier and it failed, but MVVMCross 4.0 and other plugins worked. Strange. Will get back to you on VS in a min.

**Comment by Cheesebaron** [comment]
Well the one I created in VS was also Profile259 and I could not reproduce the problem anymore with 1.2.4. Maybe it is because of the NuGet version Xamarin.Studio is using.

**Comment by Cheesebaron** [comment]
Could you try again with 1.2.5?

**Comment by RyanBuzzInteractive** [comment]
Ah, maybe. It is still on 2.something. You've probably hit the nail on the head. It installed fine on my VS so i'll just do that. Yeah, i'll try XS with 1.2.5 now.

**Comment by RyanBuzzInteractive** [comment]
1.2.5 installed in Xamarin Studio with no issues :) Thanks again dude, you have saved me a world of pain!

**Comment by Cheesebaron** [comment]
Phew. Finally :fireworks: 

Thanks for reporting this!

**Comment by PereAlmendro** [comment]
@Cheesebaron  i'm getting error "Could not install package 'Cheesebaron.MvxPlugins.Connectivity 2.2.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." in package 2.2.1
 I saw this report so maybe you want to know it.

**Comment by Cheesebaron** [comment]
Use a profile that is supported.
